ARG version
FROM almalinux:${version:-9} 
ENV course="DevOps with AWS" \
    trainer="sivakumar reddy" \
    duration="120HRS"
RUN echo "Trainer name : ${version}" > /tmp/hello.txt 
CMD ["sleep", "100"]
