FROM almalinux:9 
ENV course="DevOps with AWS" \
    trainer="sivakumar reddy" \
    duration="120HRS"
RUN echo "Trainer name : ${trainer}" > /tmp/hello.txt 
ARG USERNAME=MANOJ
RUN echo "name : ${USERNAME}" > name.txt
CMD ["sleep", "100"]
